### PR TITLE
Adding support for Rails 7.1 after recent Form Options helper changes

### PR DESCRIPTION
**Pull request by ron-shinall**
A recent Rails Edge commit (https://github.com/rails/rails/commit/77f3fc118a211c973bc3ca0b720dcba932474f89) moves the Form Options helper into select rendering classes. This is a breaking change for `country_select`. 

This PR adds support for the changes, and it has been tested with all of the versions of Rails that `country_select` supports.

If the approach I've used is not what you prefer, perhaps it will spark some additional ideas for addressing the issue.

### CODE REVIEW

**Comment by scudco** [comment]
@ron-shinall can you add `7.1` to the Github test workflow's gemfile matrix at `.github/workflows/test.yml`?

**Comment by ron-shinall** [comment]
@scudco sorry I missed that! I've added it and all checks have passed.

**Review by pmor — APPROVED** [review]

**Comment by swistaczek** [comment]
Hey @pmor, are there any chances you will be able to release an updated gem soon :)?

**Comment by pmor** [comment]
I'm traveling, but next week I should be able to take care of it.

**Pull request merged**
